version: 0.0
os: linux
files:
  - source: /FrontEndv8/dist/FrontEndv8
    destination: //opt/tomcat/webapps/explorer
  - source: /API/target/api
    destination: //opt/tomcat/webapps/explorer
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
